# Generated by Django 5.2.4 on 2025-08-24 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='文章ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='作者')),
                ('content', models.TextField(blank=True, null=True, verbose_name='文章内容')),
                ('status', models.SmallIntegerField(choices=[(1, '发布'), (0, '草稿')], default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建者')),
                ('updater', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新者')),
                ('is_deleted', models.IntegerField(default=0, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章管理',
                'db_table': 'article',
            },
        ),
    ]
