# Generated by Django 5.2.4 on 2025-08-17 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='权限ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='权限名')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='权限描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限管理',
                'db_table': 'permission',
            },
        ),
    ]
