# Generated by Django 5.2.4 on 2025-08-17 09:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('label_en', models.CharField(max_length=50, verbose_name='英文名称')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标')),
                ('type', models.IntegerField(default=1, verbose_name='菜单类型,1为目录,2为菜单,3为按钮')),
                ('router', models.CharField(blank=True, max_length=100, null=True, verbose_name='菜单路由')),
                ('rule', models.CharField(max_length=100, null=True, verbose_name='路由规则')),
                ('order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('state', models.IntegerField(default=1, verbose_name='状态,0为隐藏,1为显示')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.IntegerField(default=0, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='menu.menu', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单管理',
                'db_table': 'menu',
                'ordering': ['order'],
            },
        ),
    ]
