# Generated by Django 5.2.4 on 2025-08-03 04:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('labelEn', models.CharField(max_length=50, verbose_name='英文名称')),
                ('icon', models.CharField(max_length=50, verbose_name='图标')),
                ('key', models.CharField(max_length=100, verbose_name='菜单标识')),
                ('rule', models.CharField(max_length=100, verbose_name='路由规则')),
                ('order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否可见')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menu', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单管理',
                'db_table': 'menu',
                'ordering': ['order'],
            },
        ),
    ]
