# Generated by Django 5.2.4 on 2025-08-09 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='key',
        ),
        migrations.AddField(
            model_name='menu',
            name='router',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='菜单路由'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='menu.menu', verbose_name='父菜单'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='rule',
            field=models.CharField(max_length=100, null=True, verbose_name='路由规则'),
        ),
    ]
