# Generated by Django 5.2.4 on 2025-08-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menu_key_menu_router_alter_menu_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.IntegerField(default=1, verbose_name='菜单类型,1为目录,2为菜单,3为按钮'),
        ),
    ]
